spring:
  datasource:
    url: jdbc:tc:postgresql:13.4-buster:///kafkadbtest
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.apache.kafka.clients.NetworkClient: ERROR